services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  web:
    build: .
    command: "rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
      - db
    environment:
      DB_USER: root
      DB_PWD: example
    volumes:
      - ./:/castnxt
