development:
  clients:
    default:
      database: castnxt_development
      hosts:
        - localhost:27017
      options:
        user: 'root'
        password: 'example'
        auth_mech: :scram
        auth_source: admin
        server_selection_timeout: 30
  options:

production:
  clients:
    default:
      database: castnxt_production
      hosts:
        - db:27017
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_PWD'] %>
        auth_mech: :scram
        auth_source: admin
        server_selection_timeout: 30
  options:

test:
  clients:
    default:
      database: castnxt_test
      hosts:
        - localhost:27017
      options:
        user: 'root'
        password: 'example'
        auth_mech: :scram
        auth_source: admin
        server_selection_timeout: 30
  options: